name: 🚀 Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version, e.g.: 1.0.0'
        required: true

env:
  NODE_VERSION: 16
  NODE_ENV: production
  RELEASE_FILE_NAME: release_${{ github.event.inputs.version }}.zip
  CI : false
  
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm install
        
    - name: 🔨 Build Project 
      run: npm run build
  
    - name: List output files
      run: find build/ -print
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: build/
        server-dir: ${{ secrets.SERVER_DIR }}
        dangerous-clean-slate : true
        

    - name: Zip build
      uses: TheDoctor0/zip-release@0.7.1
      with:
          type: 'zip'
          path: build
          filename: ${{ env.RELEASE_FILE_NAME }}

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
          artifacts: ${{ env.RELEASE_FILE_NAME }}
          commit: ${{ github.sha }}
          name: v${{ github.event.inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.version }}